# Copyright (c) IncQuery Labs cPlc.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# The following secrets need to be defined: INCQUERY_USERNAME, INCQUERY_PASSWORD, INCQUERY_AUTOSAR_UML_INTEGRATION_LICENSE

on:
  push
jobs:
  AutosarUml:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      
      - name: Backup EA Project File
        id: backupEAProjectFile
        run: |
          $eaFileName = "counting-logic"
          $eaFileExtension = "qeax"
          $originalEaProjectFile = '${{ runner.temp }}/' + $eaFileName + '-old.' + $eaFileExtension
          $reimportedEaProjectFile = '.\' + $eaFileName + '.' + $eaFileExtension
          Copy-Item -Path $reimportedEaProjectFile -Destination $originalEaProjectFile
          echo "originalEAProjectFile=$originalEaProjectFile" >> $env:GITHUB_OUTPUT
          echo "reimportedEAProjectFile=$reimportedEaProjectFile" >> $env:GITHUB_OUTPUT
          echo "fileName=$eaFileName" >> $env:GITHUB_OUTPUT
          echo "fileExtension=$eaFileExtension" >> $env:GITHUB_OUTPUT
      
      - name: Run IncQuery AUTOSAR-UML Bridge
        uses: ./
        with:
          arxml_folder_path: example-arxml
          ea_model_file_path: "${{steps.backupEAProjectFile.outputs.reimportedEAProjectFile}}"
          incquery_username: "${{ secrets.INCQUERY_USERNAME }}"
          incquery_password: "${{ secrets.INCQUERY_PASSWORD }}"
          license: "${{ secrets.INCQUERY_AUTOSAR_UML_INTEGRATION_LICENSE }}"
      #Install LieberLieber LemonTree.Automation on the Action-Runner and prepare the license
      #the secrets.LTALICENSE contains the text from the License File provided
      - name: GetLTA
        uses: LieberLieber/setup-LemonTree.Automation@v1
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}}    
      #Diff Check between the modified files     
      - name: Calculate differences between the original and reimported EA projects
        id: diffOutput
        run: | 
          $diffFile = "${{ runner.temp }}/${{steps.backupEAProjectFile.outputs.fileName}}-${{steps.backupEAProjectFile.outputs.fileExtension}}-diff.ltsfs"
          &'${{steps.GetLTA.outputs.LemonTreeAutomationExecutable}}' diff --base '${{steps.backupEAProjectFile.outputs.originalEAProjectFile}}' --theirs '${{steps.backupEAProjectFile.outputs.originalEAProjectFile}}' --mine '${{steps.backupEAProjectFile.outputs.reimportedEAProjectFile}}' --sfs $diffFile
          echo "diffSessionFile=$diffFile" >> $env:GITHUB_OUTPUT
      #Archive Session Files
      - name: Archive Session Files
        uses: actions/upload-artifact@v3
        with:
          name: Diff Session File
          path: '${{steps.diffOutput.outputs.diffSessionFile}}'
          retention-days: 5
