# Copyright (c) LieberLieber Software GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Create Pull Request
on:
 push:
  branches-ignore:
    - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})"  >> $GITHUB_OUTPUT
        id: extract_branch

      # TODO:
      # 1) Look for exisiting Pull Request
      # 2) Try to crete a Pull Request - learn from PCS Repo.
      
      # - name: pull-request
      #   uses: repo-sync/pull-request@v2
      #   with:
      #     destination_branch: "main"
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     pr_label: "automated pr"
      #     pr_title: "${{ steps.extract_branch.outputs.branch }}"
      #     pr_allow_empty: true
      #     pr_draft: true
 
     
    
