# Copyright (c) Robert Bosch GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: LTA Auto Deploy Demo - ConsistencyCheck

on:
 push:

env:
  ModelName: DemoModel
  ModelExtension: eapx
  LemonTreePackageURL: https://nexus.lieberlieber.com/repository/lemontree-release/LemonTree.Automation/LemonTree.Automation.Zip_Deploy.zip
  LemonTreeArchiveName: LTA.zip
  LemonTreeAutomationExecutable: LTA\LemonTree.Automation.exe
  TempLicense: lta.lic
  

jobs:
  ConsistencyCheck:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Get LemonTree
        run: |
         while (Test-Path Alias:curl) {Remove-Item Alias:curl} #remove the alias binding from curl to Invoke-WebRequest
         curl "${{env.LemonTreePackageURL}}" --output ${{env.LemonTreeArchiveName}} -k
         Expand-Archive ${{env.LemonTreeArchiveName}} -DestinationPath LTA\ -Force

      - name: Create LemonTreeLicense
        run: |
          '${{secrets.LTALICENSE}}' | Out-File -FilePath ${{env.TempLicense}}

      - name: ConsistencyCheck
        run: |
          &"${{env.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model ${{env.ModelName}}.${{env.ModelExtension}} --License ${{env.TempLicense}}
 
     
    