# Copyright (c) Robert Bosch GmbH
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Test>GetLemonTreeAutomation

on:
 push:

env:
  ModelName: DemoModel
  ModelExtension: eapx
  LemonTreeAutomationExecutable: LTA\LemonTree.Automation.exe

jobs:
  ConsistencyCheck:
    defaults:
      run:
        shell: pwsh
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: GetLTA
        uses: ./Action/GetLemonTreeAutomation/
        id: GetLTA
        with:
          License: ${{secrets.LTALICENSE}}
      
      - name: Set Environment LemonTreeAutomationExecutable
        run: |
           $env.LemonTreeAutomationExecutable = $steps.GetLTA.outputs.LemonTreeAutomationExecutable

      - name: ConsistencyCheck
        run: |
          &"${{env.LemonTreeAutomationExecutable}}" ConsistencyCheck --Model ${{env.ModelName}}.${{env.ModelExtension}}
 
     
    